services:
  - type: web
    name: frontend
    env: docker
    image:
      url: docker.io/sandesh1000/chatgpt-frontend:latest
    envVars:
      - key: VITE_BASE_URL
        value: http://localhost:4000
    plan: free
    region: oregon

  - type: web
    name: gateway
    env: docker
    image:
      url: docker.io/sandesh1000/chatgpt-gateway:latest
    envVars:
      - key: PORT
        value: 4000
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: FRONTEND_URL
        value: http://localhost:3000
      - key: AUTH_SERVICE_URL
        value: http://localhost:4001
      - key: CHAT_SERVICE_URL
        value: http://localhost:4002
    plan: free
    region: oregon

  - type: web
    name: auth
    env: docker
    image:
      url: docker.io/sandesh1000/chatgpt-auth:latest
    envVars:
      - key: PORT
        value: 4001
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRY
        value: 1d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: http://localhost:4001/google/callback
      - key: MONGODB_ATLAS_URI
        sync: false
      - key: ATLAS_DB_NAME
        value: chatgpt-auth
      - key: FRONTEND_URL
        value: http://localhost:3000
    plan: free
    region: oregon

  - type: web
    name: chat
    env: docker
    image:
      url: docker.io/sandesh1000/chatgpt-chat:latest
    envVars:
      - key: PORT
        value: 4002
      - key: GOOGLE_API_KEY
        sync: false
      - key: MONGODB_CLIENT
        sync: false
      - key: FRONTEND_URL
        value: http://localhost:3000
      - key: GATEWAY_URL
        value: http://localhost:4000
    plan: free
    region: oregon
